In [28]:
import pandas as pd

#Task 1

In [29]:
data1={'Index':[1,2,3,4]
    ,'Name':['Paul','Mridul','Jack','Bob']
      ,'Age':[10,11,12,13],
      'Gender':['M','F','M','M'],
      }
df= pd.DataFrame(data1)
df

   Index    Name  Age Gender
0      1    Paul   10      M
1      2  Mridul   11      F
2      3    Jack   12      M
3      4     Bob   13      M

#Task 2

In [30]:
df.columns=['Randomvalue 1','Randomvalue 2','Randomvalue 3','Randomvalue 4']
df

   Randomvalue 1 Randomvalue 2  Randomvalue 3 Randomvalue 4
0              1          Paul             10             M
1              2        Mridul             11             F
2              3          Jack             12             M
3              4           Bob             13             M

#Task 3

In [31]:
df.info

<bound method DataFrame.info of    Randomvalue 1 Randomvalue 2  Randomvalue 3 Randomvalue 4
0              1          Paul             10             M
1              2        Mridul             11             F
2              3          Jack             12             M
3              4           Bob             13             M>

In [32]:
df.describe()

       Randomvalue 1  Randomvalue 3
count       4.000000       4.000000
mean        2.500000      11.500000
std         1.290994       1.290994
min         1.000000      10.000000
25%         1.750000      10.750000
50%         2.500000      11.500000
75%         3.250000      12.250000
max         4.000000      13.000000

#TASK 4

In [33]:
df.isnull().sum()

Randomvalue 1    0
Randomvalue 2    0
Randomvalue 3    0
Randomvalue 4    0
dtype: int64

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Randomvalue 1  4 non-null      int64
 1   Randomvalue 2  4 non-null      object
 2   Randomvalue 3  4 non-null      int64
 3   Randomvalue 4  4 non-null      object
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

#Task 5

In [35]:
df.loc[0:4,'Randomvalue 2':'Randomvalue 3']

  Randomvalue 2  Randomvalue 3
0          Paul             10
1        Mridul             11
2          Jack             12
3           Bob             13

In [36]:
df.iloc[0:4,1:3]

  Randomvalue 2  Randomvalue 3
0          Paul             10
1        Mridul             11
2          Jack             12
3           Bob             13

**EXTRA QUESTIONS PROVIDED BY MA'AM**

In [37]:
import pandas as pd

In [38]:
data={'Index':[1,2,3,4,5,6,7,8,9,10]
    ,'Name':['Paul','Mridul','Jack','Bob','Alice','Hari','Om','Luis','Jay','Radha']
      ,'Age':[10,11,12,13,14,15,16,25,14,13],
      'Class':[10,10,9,12,8,7,6,5,7,8]
      ,'Gender':['M','F','M','M','F','M','M','M','M','F'],
      }
df= pd.DataFrame(data)

In [39]:
df

   Index    Name  Age  Class Gender
0      1    Paul   10     10      M
1      2  Mridul   11     10      F
2      3    Jack   12      9      M
3      4     Bob   13     12      M
4      5   Alice   14      8      F
5      6    Hari   15      7      M
6      7      Om   16      6      M
7      8    Luis   25      5      M
8      9     Jay   14      7      M
9     10   Radha   13      8      F

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Index   10 non-null     int64
 1   Name    10 non-null     object
 2   Age     10 non-null     int64
 3   Class   10 non-null     int64
 4   Gender  10 non-null     object
dtypes: int64(3), object(2)
memory usage: 528.0+ bytes

In [41]:
df.describe()

          Index        Age      Class
count  10.00000  10.000000  10.000000
mean    5.50000  14.300000   8.200000
std     3.02765   4.164666   2.097618
min     1.00000  10.000000   5.000000
25%     3.25000  12.250000   7.000000
50%     5.50000  13.500000   8.000000
75%     7.75000  14.750000   9.750000
max    10.00000  25.000000  12.000000

In [42]:
df.loc[3]

Index       4
Name      Bob
Age        13
Class      12
Gender      M
Name: 3, dtype: object

In [43]:
df.isnull()

   Index   Name    Age  Class  Gender
0  False  False  False  False   False
1  False  False  False  False   False
2  False  False  False  False   False
3  False  False  False  False   False
4  False  False  False  False   False
5  False  False  False  False   False
6  False  False  False  False   False
7  False  False  False  False   False
8  False  False  False  False   False
9  False  False  False  False   False

**END OF THE ASSIGNMENT**

**THANK YOU**